export type Review = {
  author: string;
  meta: string;
  when: string;
  rating: number;
  text: string;
  tag: string;
};

export const REVIEWS: Review[] = [
  {
    author: "Bharat CJ",
    meta: "Local Guide, 25 reviews",
    when: "a year ago",
    rating: 5,
    text: "I recently visited RUDRA DENTAL in Anakaputhur and had an excellent experience! The clinic is very welcoming and the staff is incredibly friendly and professional. From routine check-ups to advanced treatments, they offer comprehensive dental care.",
    tag: "Friendly doctor",
  },
  {
    author: "Iniyabranidharan Iniya",
    meta: "3 reviews",
    when: "2 months ago",
    rating: 5,
    text: "Yesterday I had a severe tooth ache, so I visited Rudra Dental Clinic. I had a wonderful experience. The clinic is extremely clean and hygienic, and the entire team is very professional and caring.",
    tag: "Friendly doctor",
  },
  {
    author: "S Mariappan",
    meta: "Local Guide, 21 reviews",
    when: "3 months ago",
    rating: 5,
    text: "Seven years back one of my teeth had been removed and replaced by artificial removable teeth. Since it was inconvenient, I threw it and left the gap as it is. Two months back, I felt that the adjacent teeth were getting weaker. I went to Rudra Dental.",
    tag: "Overall experience",
  },
  {
    author: "Geethashree Gunasekaran",
    meta: "Local Guide, 104 reviews",
    when: "2 months ago",
    rating: 5,
    text: "I recently visited Rudra Dental Clinic for a regular teeth cleaning, and the service was fantastic! My teeth are noticeably cleaner, and the price was really reasonable. I also took my husband after he returned from abroad, and he had a great experience as well. Highly recommend them!",
    tag: "Teeth cleaning",
  },
  {
    author: "Suriya Scooby",
    meta: "6 reviews",
    when: "5 months ago",
    rating: 5,
    text: "Visited Rudra Dental Clinic for my 5-year-old son tooth cavity treatment. The doctor handled him with so much patience and care, which made my son feel very comfortable. The clinic is very clean and hygienic. Overall a very good experience.",
    tag: "Cavity treatment",
  },
  {
    author: "Plato Bose",
    meta: "3 reviews",
    when: "6 months ago",
    rating: 5,
    text: "Last week I had a root canal, filling, and crown placement done by Dr. Gopi, and I cannot recommend him enough. The clinic is well-equipped with the latest dental technology, and Dr. Gopi utilizes these tools to their maximum potential.",
    tag: "Root canal",
  },
  {
    author: "Selvan Suresh",
    meta: "Local Guide, 11 reviews",
    when: "6 months ago",
    rating: 5,
    text: "I recently visited Rudra Dental for a root canal treatment followed by fixing a dual cap on one of my teeth, and I must say I am extremely satisfied with the entire experience.",
    tag: "Root canal",
  },
  {
    author: "Girija Ganesan",
    meta: "12 reviews",
    when: "6 months ago",
    rating: 5,
    text: "Amazing dental cleaning service! The staff was patient, gentle, and very professional. They explained each step and made the visit relaxing. Perfect for anyone who gets nervous at the dentist.",
    tag: "Teeth cleaning",
  },
  {
    author: "Packiam G",
    meta: "1 review",
    when: "10 months ago",
    rating: 5,
    text: "I recently had a root canal treatment done, and I am extremely satisfied with the entire experience. The doctor explained each step clearly, which helped reduce my anxiety. The procedure was smooth, almost painless, and handled with great care.",
    tag: "Root canal",
  },
  {
    author: "Pitchi Parimalam",
    meta: "1 review",
    when: "6 months ago",
    rating: 5,
    text: "Dr Gopinath is very polite, he explained the causes for my teeth pain and treatment clearly. Modern equipment and painless treatment made me very comfortable. Very punctual, after treatment followup is a plus point. Recommend this clinic wholeheartedly.",
    tag: "Painless care",
  },
  {
    author: "Abinaya Arivalagan",
    meta: "2 reviews",
    when: "10 months ago",
    rating: 5,
    text: "I was nervous about my first dental visit, but the doctor was so compassionate and made me feel completely comfortable. He explained everything clearly and gave me a thorough check-up. I had a painless experience.",
    tag: "Painless care",
  },
  {
    author: "Madhu Mathi",
    meta: "8 reviews",
    when: "6 months ago",
    rating: 5,
    text: "Excellent service and good experience. Low cost treatment. Highly recommended.",
    tag: "Affordable",
  },
  {
    author: "Prem Karthik",
    meta: "5 reviews",
    when: "a year ago",
    rating: 5,
    text: "I started my ortho braces treatment. Doctor has been very supportive and has provided proper guidance for dental care. I recommend Rudra Dental, one of the best clinics.",
    tag: "Braces",
  },
  {
    author: "Vijay Prakash",
    meta: "Local Guide, 601 reviews",
    when: "a year ago",
    rating: 5,
    text: "I had a very pleasant experience at this dental hospital and would highly recommend it to anyone looking for quality dental care. The hospital is easily accessible, conveniently located, and has a clean, professional environment.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Shamir Khan",
    meta: "4 reviews",
    when: "9 months ago",
    rating: 5,
    text: "I had a wonderful experience with my check up with doctor Gopinath. I must say he is one of the best doctors I have met. Not only did he take care of my dental concern but he explained the process in detail, and even made my kids first dental experience a good one.",
    tag: "Kids dentistry",
  },
  {
    author: "Vadivel Nataraj",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "I recently underwent a root canal treatment at this clinic and was thoroughly impressed. The professional doctors made me feel completely at ease, and the procedure was surprisingly quick and painless.",
    tag: "Root canal",
  },
  {
    author: "Meenu Esha",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "I recently visited here and was thoroughly impressed with the exceptional care and service I received. The facilities were modern and clean, and the staff were friendly, professional, and attentive.",
    tag: "Friendly doctor",
  },
  {
    author: "Prakash Raja",
    meta: "6 reviews",
    when: "a year ago",
    rating: 5,
    text: "I visited Rudra Dental for a general dental check up. Dr. Gopinath, chief dental surgeon, did teeth cleaning and filling. I am satisfied with the treatment given. Sir explained about the treatment before proceeding.",
    tag: "Cavity treatment",
  },
  {
    author: "Chandru",
    meta: "6 reviews",
    when: "9 months ago",
    rating: 5,
    text: "One of the best dental clinics in Chennai. Dr. Gopinath is an extremely friendly and approachable doctor, and the overall experience at his clinic is truly excellent.",
    tag: "Friendly doctor",
  },
  {
    author: "Hari Singam",
    meta: "Local Guide, 10 reviews",
    when: "8 months ago",
    rating: 5,
    text: "Good hospitality. Dr. Gopi very friendly. Fully equipped with latest technology. Premium treatment at affordable price.",
    tag: "Affordable",
  },
  {
    author: "Madhumitha Madhu",
    meta: "3 reviews",
    when: "3 months ago",
    rating: 5,
    text: "Well experienced doctors and good treatment.",
    tag: "Overall experience",
  },
  {
    author: "Vignesh Raja",
    meta: "4 reviews",
    when: "a year ago",
    rating: 5,
    text: "The last time we saw Dr. Gopinath was fantastic. He took the time to explain everything clearly, answered all my questions, and made sure I was comfortable throughout the cleaning. He did not push any unnecessary treatments and gave me helpful advice for maintaining my oral health.",
    tag: "Teeth cleaning",
  },
  {
    author: "Janaki Ganesh",
    meta: "6 reviews",
    when: "a year ago",
    rating: 5,
    text: "It is a good experience. Since I had a fear of going to a dental clinic, I was avoiding it. But I came here finally and the doctor made me comfortable and did the root canal procedure. I feel very happy that in a period of time I forgot my fear and completed the procedure.",
    tag: "Root canal",
  },
  {
    author: "Ajith Sekhar",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "I had a great experience at Rudra Dental Clinic. The clinic is clean and welcoming, and the staff are professional and friendly. The dental care provided was excellent, and they ensured my comfort throughout the visit.",
    tag: "Friendly doctor",
  },
  {
    author: "Keerthana Bakthavatchalam",
    meta: "Local Guide, 12 reviews",
    when: "a year ago",
    rating: 5,
    text: "I had a wonderful experience at Rudra Dental Clinic. Dr. Gopinath and his team are highly skilled and professional. They take the time to explain every detail of the treatment and ensure you feel comfortable throughout the procedures.",
    tag: "Painless care",
  },
  {
    author: "Sri Sant K",
    meta: "1 review",
    when: "6 months ago",
    rating: 5,
    text: "All the doctors are very friendly, and the clinic is clean and hygienic. Must try.",
    tag: "Friendly doctor",
  },
  {
    author: "Madhina Khan",
    meta: "4 reviews",
    when: "a year ago",
    rating: 5,
    text: "Thank you so much. I also had a great experience. The clinic is very clean and hygienic. I felt positive vibes. Especially the environment made me relaxed and fearless. My dentist is not only a dentist but also a dental artist.",
    tag: "Painless care",
  },
  {
    author: "Subhadeepan K",
    meta: "Local Guide, 19 reviews",
    when: "a year ago",
    rating: 5,
    text: "Dr. Gopinath and Rudra Dental clinic are simply outstanding! A couple of months ago, I underwent treatment for seven teeth, which included two surgeries and a root canal. From start to finish, the care I received was exceptional.",
    tag: "Root canal",
  },
  {
    author: "Hameed Nawaaz",
    meta: "6 reviews",
    when: "a year ago",
    rating: 5,
    text: "Dr. Gopinath is an excellent doctor. The way he spoke with kids and the way he treated them was so good, and also the charges are affordable. I would recommend this clinic to my friends and neighbours.",
    tag: "Kids dentistry",
  },
  {
    author: "Sivagandan",
    meta: "2 reviews",
    when: "10 months ago",
    rating: 5,
    text: "A perfect place for dental treatment. Good experience. Staff are very professional and friendly.",
    tag: "Friendly doctor",
  },
  {
    author: "Vamsee Krishna",
    meta: "3 reviews",
    when: "2 years ago",
    rating: 5,
    text: "Good clinic with modern decor and comfortable seating. Highly recommended dental clinic. Extremely professional team of doctors and staff. I am highly satisfied by the treatment given by the doctor and happy with the results.",
    tag: "Painless care",
  },
  {
    author: "Madhu Augustine",
    meta: "11 reviews",
    when: "2 years ago",
    rating: 5,
    text: "The dental clinic is known for its five-star hygiene standards and exceptional work quality. The doctor is multilingual, speaking all South Indian languages as well as Hindi. I highly recommend it.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Manasha K",
    meta: "1 review",
    when: "4 months ago",
    rating: 5,
    text: "Excellent clinic and highly recommended clinic.",
    tag: "Overall experience",
  },
  {
    author: "Kalidasan J",
    meta: "4 reviews",
    when: "a year ago",
    rating: 5,
    text: "I recently visited here and was thoroughly impressed with the exceptional care and service I received. The facilities were modern and clean, and the staff were friendly, professional, and attentive.",
    tag: "Friendly doctor",
  },
  {
    author: "Palanisamy",
    meta: "2 reviews",
    when: "4 months ago",
    rating: 5,
    text: "Very good experience clinic.",
    tag: "Overall experience",
  },
  {
    author: "Hannah Ranjini",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "I have always been impressed by their professionalism and quality of service. Dr Gopinath here is so knowledgeable and explains everything in simple terms.",
    tag: "Staff and service",
  },
  {
    author: "Cresswell Dcruz",
    meta: "5 reviews",
    when: "a year ago",
    rating: 5,
    text: "A very good dental clinic, thanks very much for the painless root canal treatment I underwent. A good place for all dental issues and affordable.",
    tag: "Root canal",
  },
  {
    author: "Sushmitha A",
    meta: "1 review",
    when: "6 months ago",
    rating: 5,
    text: "Excellent clinic. Nice ambience.",
    tag: "Clinic and hygiene",
  },
  {
    author: "VG Mariyammal",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "I recently visited here and was thoroughly impressed with the exceptional care and service I received. The facilities were modern and clean, and the staff were friendly, professional, and attentive.",
    tag: "Friendly doctor",
  },
  {
    author: "Mani Bharathi",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "One of the best clinics in Anakaputhur. I would recommend this dental clinic to anyone looking for a reliable dental service.",
    tag: "Staff and service",
  },
  {
    author: "Harin Niveth",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "I have visited Rudra Dental and had a good experience. It was so comfortable for me. They were so kind and humble and their services were really good.",
    tag: "Painless care",
  },
  {
    author: "Rajeswari Kanagavel",
    meta: "2 reviews",
    when: "2 months ago",
    rating: 5,
    text: "Good and excellent service.",
    tag: "Staff and service",
  },
  {
    author: "Preethi V",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "We went for the treatment of dental implant and tooth cleaning. Excellent service with a friendly doctor at Rudra Dental.",
    tag: "Dental implant",
  },
  {
    author: "Kannan Sankar",
    meta: "6 reviews",
    when: "10 months ago",
    rating: 5,
    text: "Experienced and best care taken by Mr. Gopinath sir.",
    tag: "Overall experience",
  },
  {
    author: "Rathna Vel S",
    meta: "5 reviews",
    when: "a year ago",
    rating: 5,
    text: "One of the best dental doctors I have ever consulted. Good man with a good heart. He knows what he does.",
    tag: "Overall experience",
  },
  {
    author: "Dileep Kumar",
    meta: "4 reviews",
    when: "a year ago",
    rating: 5,
    text: "Nice treatment. Very neat and hygienic clinic.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Aswin Sachith",
    meta: "5 reviews",
    when: "a year ago",
    rating: 5,
    text: "Clinic is very clean and hygienic. I had a very good experience here.",
    tag: "Clinic and hygiene",
  },
  {
    author: "S Murugaraj",
    meta: "9 reviews",
    when: "a year ago",
    rating: 5,
    text: "The team are very skilled and their care of patients was well appreciated.",
    tag: "Friendly doctor",
  },
  {
    author: "Felix Augustine",
    meta: "Local Guide, 14 reviews",
    when: "7 months ago",
    rating: 5,
    text: "A nice, homely clinic and a friendly doctor.",
    tag: "Friendly doctor",
  },
  {
    author: "Selvamurugesan Shanmugam",
    meta: "2 reviews",
    when: "2 years ago",
    rating: 5,
    text: "Nice treatment and customer care. Facilities, advanced treatment equipment, quality of treatment, cost of treatment and time management are good.",
    tag: "Affordable",
  },
  {
    author: "Jayaramamoorthy K",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Rudra Dental Clinic is one of the trusted experiences for me. Highly recommend.",
    tag: "Overall experience",
  },
  {
    author: "Priya Rajkumar",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "The clinic is always clean and well-organized, and the appointments run on time.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Jahnavi Buri",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Well taken care of customers. Had a safe checkup with good offers.",
    tag: "Affordable",
  },
  {
    author: "Pankaj Ahlawat",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "A best clinic for dental treatment. Visit for your dental problems. A great experience overall.",
    tag: "Overall experience",
  },
  {
    author: "Gowri M",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Very good treatment and well cleaned environment.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Yashpal Birdhana",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "A great dental clinic for teeth. Please visit one time for the best treatment.",
    tag: "Staff and service",
  },
  {
    author: "Durai",
    meta: "3 reviews",
    when: "7 months ago",
    rating: 5,
    text: "Good one. Visit all.",
    tag: "Overall experience",
  },
  {
    author: "Bala Chandar",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good treatment for root canal. Clean and neat environment.",
    tag: "Root canal",
  },
  {
    author: "Sasikala S",
    meta: "6 reviews",
    when: "2 years ago",
    rating: 5,
    text: "Very good facility for dental care. All the staff are very friendly and professional.",
    tag: "Friendly doctor",
  },
  {
    author: "Best Trading",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Professional doctors and staff. Neat and clean. Good hospitality.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Deepak Namdev",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Very good treatment, nice and hygienic environment.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Sathiya B",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Thank you so much Dr. Gopi sir for your treatment.",
    tag: "Overall experience",
  },
  {
    author: "Chitra Good B",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Dr. Gopi sir is very kind and he did the treatment very well.",
    tag: "Friendly doctor",
  },
  {
    author: "Krishna Chaitanya Nunna",
    meta: "14 reviews",
    when: "2 years ago",
    rating: 5,
    text: "I got my implant treatment done by Dr. Gopinath. He explained the whole process.",
    tag: "Dental implant",
  },
  {
    author: "JK",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Kind and friendly. Also gave a good solution to my cavity problem.",
    tag: "Cavity treatment",
  },
  {
    author: "Lakshmi Vararuchi",
    meta: "1 review",
    when: "2 years ago",
    rating: 5,
    text: "Nice experience, good hospitality, good ambience, good treatment.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Karthik S",
    meta: "7 reviews",
    when: "a year ago",
    rating: 5,
    text: "Completely satisfied. Excellent treatment.",
    tag: "Overall experience",
  },
  {
    author: "Vishnu Sankar",
    meta: "1 review",
    when: "2 years ago",
    rating: 5,
    text: "Super friendly staff. Good service and well maintained.",
    tag: "Friendly doctor",
  },
  {
    author: "Vinay Bindra",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Very nice dental clinic and comfortable seating.",
    tag: "Painless care",
  },
  {
    author: "Sanjeet Kaushik",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Very good clinic and comfortable seating.",
    tag: "Painless care",
  },
  {
    author: "Udhaya Kavin",
    meta: "5 reviews",
    when: "a year ago",
    rating: 5,
    text: "Thanks to all. Very kind staff and quality and quick response.",
    tag: "Friendly doctor",
  },
  {
    author: "Jothibasu Ramachary",
    meta: "3 reviews",
    when: "8 months ago",
    rating: 5,
    text: "Very good treatment.",
    tag: "Overall experience",
  },
  {
    author: "Sachin Ahlawat",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Nice clinic, modern decor and seating.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Praveen Kalonia",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Very good clinic for dental. Nice.",
    tag: "Overall experience",
  },
  {
    author: "Avinash Dhingra",
    meta: "4 reviews",
    when: "a year ago",
    rating: 5,
    text: "Service is very good and staff is also very humble.",
    tag: "Friendly doctor",
  },
  {
    author: "Insight Rehabs",
    meta: "Local Guide, 127 reviews",
    when: "11 months ago",
    rating: 5,
    text: "Excellent consultation and treatment.",
    tag: "Overall experience",
  },
  {
    author: "Jeevan K",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good clinic and good hospitality.",
    tag: "Staff and service",
  },
  {
    author: "Chimbuanbu Munnar",
    meta: "6 reviews",
    when: "a year ago",
    rating: 5,
    text: "Very good treatment and good responsibility.",
    tag: "Overall experience",
  },
  {
    author: "Arasu Suba",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Excellent service. Satisfied.",
    tag: "Staff and service",
  },
  {
    author: "Anjali Madaan",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good treatment and good care.",
    tag: "Overall experience",
  },
  {
    author: "Kumaran Kumar",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Good and hygienic clinic.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Mervin Victor",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good experience with the doctor.",
    tag: "Overall experience",
  },
  {
    author: "Harini Nivetha",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Excellent hospitality and service.",
    tag: "Staff and service",
  },
  {
    author: "Shahanawaz Khan",
    meta: "2 reviews",
    when: "2 years ago",
    rating: 5,
    text: "Awesome experience at Rudra Dental.",
    tag: "Overall experience",
  },
  {
    author: "Preetha Suresh",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "It is a great experience to me.",
    tag: "Overall experience",
  },
  {
    author: "Rasheeda Pareed",
    meta: "6 reviews",
    when: "a year ago",
    rating: 5,
    text: "Very good service.",
    tag: "Staff and service",
  },
  {
    author: "Manju",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Super and completely satisfied.",
    tag: "Overall experience",
  },
  {
    author: "Aarthi Mohan",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Nice ambience with modern technology.",
    tag: "Clinic and hygiene",
  },
  {
    author: "Suraj Rebel",
    meta: "9 reviews",
    when: "2 years ago",
    rating: 5,
    text: "Good place and friendly staff.",
    tag: "Friendly doctor",
  },
  {
    author: "Sowmya Mach",
    meta: "4 reviews",
    when: "2 years ago",
    rating: 5,
    text: "Best dentist in Chennai.",
    tag: "Overall experience",
  },
  {
    author: "Pankaj Kumar",
    meta: "5 reviews",
    when: "a year ago",
    rating: 5,
    text: "Absolutely the right place.",
    tag: "Overall experience",
  },
  {
    author: "Jitender Kumar",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Multi language talent doctor.",
    tag: "Overall experience",
  },
  {
    author: "Suresh Babu K V",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Very nice experience.",
    tag: "Overall experience",
  },
  {
    author: "Sudhakaran K S",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Super, in all respects.",
    tag: "Overall experience",
  },
  {
    author: "Mubina T",
    meta: "2 reviews",
    when: "2 years ago",
    rating: 5,
    text: "Good treatment given.",
    tag: "Overall experience",
  },
  {
    author: "Sorna Latha",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Super caring hospital.",
    tag: "Friendly doctor",
  },
  {
    author: "Meera Muthu",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Excellent treatment.",
    tag: "Overall experience",
  },
  {
    author: "Athira Harikkuttan",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Good treatment.",
    tag: "Overall experience",
  },
  {
    author: "Syamalakumari Kolli",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good service.",
    tag: "Staff and service",
  },
  {
    author: "Hariharan K",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Nice clinic.",
    tag: "Overall experience",
  },
  {
    author: "Vanaparthi Leenitha",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good doctors.",
    tag: "Overall experience",
  },
  {
    author: "Vijay Saini",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Nice dental and fantastic.",
    tag: "Overall experience",
  },
  {
    author: "Suman Kumar",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Good dental clinic.",
    tag: "Overall experience",
  },
  {
    author: "Nagulesh N",
    meta: "2 reviews",
    when: "a year ago",
    rating: 5,
    text: "Very good service.",
    tag: "Staff and service",
  },
  {
    author: "Athul Das K V",
    meta: "3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Nice experience.",
    tag: "Overall experience",
  },
  {
    author: "Rahul Singhal",
    meta: "8 reviews",
    when: "a year ago",
    rating: 5,
    text: "Nice one.",
    tag: "Overall experience",
  },
  {
    author: "Anoop Singh",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Nice clinic.",
    tag: "Overall experience",
  },
  {
    author: "Rudra Sambharwal",
    meta: "1 review",
    when: "a year ago",
    rating: 5,
    text: "Good clinic dental.",
    tag: "Overall experience",
  },
  {
    author: "Ravi Keb",
    meta: "12 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good service.",
    tag: "Staff and service",
  },
  {
    author: "Farish B",
    meta: "1 review",
    when: "3 weeks ago",
    rating: 5,
    text: "Very good service and good treatment.",
    tag: "Staff and service",
  },
  {
    author: "Gaya3 G",
    meta: "4 reviews",
    when: "3 months ago",
    rating: 5,
    text: "Good clinic.",
    tag: "Overall experience",
  },
  {
    author: "Tanushiya Hemadhri",
    meta: "2 reviews",
    when: "3 months ago",
    rating: 5,
    text: "I used to hesitate going to dental clinics because I was scared of the pain, but after visiting this clinic, I felt completely comfortable. The doctor was very patient, took time to make me feel relaxed, and explained the procedure clearly.",
    tag: "Painless care",
  },
  {
    author: "Valarmathi Sri",
    meta: "1 review, translated from Tamil",
    when: "3 months ago",
    rating: 5,
    text: "The experience of getting treatment at Rudra Dental Clinic was very good. The doctors were very patient in explaining and providing treatment. The clinic was clean and the staff was friendly. I am very satisfied.",
    tag: "Friendly doctor",
  },
  {
    author: "Ravinder Kumar",
    meta: "Local Guide, 3 reviews",
    when: "a year ago",
    rating: 5,
    text: "Good treatment.",
    tag: "Overall experience",
  },
  {
    author: "Abhishek Sharma",
    meta: "1 review, translated from Hindi",
    when: "a year ago",
    rating: 5,
    text: "Very good.",
    tag: "Overall experience",
  },
  {
    author: "Iyammal Ani",
    meta: "1 review, translated from Tamil",
    when: "a year ago",
    rating: 5,
    text: "Super.",
    tag: "Overall experience",
  },
];

export const REVIEW_TOPICS = [
  { label: "Overall experience", count: 40 },
  { label: "Friendly doctor", count: 19 },
  { label: "Clinic and hygiene", count: 13 },
  { label: "Staff and service", count: 12 },
  { label: "Painless care", count: 9 },
  { label: "Root canal", count: 8 },
  { label: "Affordable", count: 4 },
  { label: "Teeth cleaning", count: 3 },
  { label: "Cavity treatment", count: 3 },
  { label: "Kids dentistry", count: 2 },
  { label: "Dental implant", count: 2 },
  { label: "Braces", count: 1 },
];
