export const SEO_KEYWORDS: string[] = [
  "Rudra Dental",
  "Dental Care",
  "Dental Care Chennai",
  "Root Canal",
  "Root Canal Specialist",
  "Root Canal Treatment",
  "Root Canal Treatment in Anakaputhur",
  "Root Canal Treatment in Pallavaram",
  "Root Canal Treatment in Pammal",
  "Root Canal Treatment in Chromepet",
  "Root Canal Treatment in Kundrathur",
  "Root Canal Treatment in Tambaram",
  "Root Canal Treatment in Chennai",
  "Root Canal Specialist Pallavaram",
  "Root Canal Specialist in Chennai",
  "Dental Implants",
  "Dental Implants in Anakaputhur",
  "Dental Implants in Pallavaram",
  "Dental Implants in Pammal",
  "Dental Implants in Chromepet",
  "Dental Implants in Kundrathur",
  "Dental Implants in Tambaram",
  "Dental Implants near Porur",
  "Dental Implants in Chennai",
  "Full Mouth Dental Implants in Chennai",
  "Affordable Root Canal Treatment in Pammal",
  "Orthodontic Treatment",
  "Orthodontic Treatment in Chromepet",
  "Orthodontic Treatment in Pallavaram",
  "Orthodontic Treatment in Anakaputhur",
  "Orthodontic Treatment in Tambaram",
  "Orthodontist in Pallavaram",
  "Orthodontist in Anakaputhur",
  "Orthodontist in Kundrathur",
  "Orthodontist near Pammal",
  "Best Orthodontist in Chennai",
  "Best Orthodontic Treatment in Kundrathur",
  "Orthodontics in Anakaputhur",
  "Orthodontics in Chromepet",
  "Orthodontics in Pallavaram",
  "Best Orthodontics in Pallavaram",
  "Braces",
  "Braces in Chromepet",
  "Braces in Anakaputhur",
  "Braces in Pallavaram",
  "Braces in Tambaram",
  "Braces in Kundrathur",
  "Braces in Chennai",
  "Braces for adults in Pallavaram",
  "Braces for kids in Pammal",
  "Dental braces in Kundrathur",
  "Dental braces in Meenambakkam",
  "Clear aligners",
  "Clear Aligners in Chennai",
  "Clear Aligners in Anakaputhur",
  "Clear Aligners in Pallavaram",
  "Clear Aligners in Pammal",
  "Clear Aligners in Chromepet",
  "Clear Aligners in Kundrathur",
  "Clear Aligners near Porur",
  "Clear Aligners in Meenambakkam",
  "Clear Aligners for Teens in Chromepet",
  "Invisalign",
  "Invisalign in Chennai",
  "Invisalign in Anakaputhur",
  "Invisalign in Pallavaram",
  "Invisalign in Pammal",
  "Invisalign in Chromepet",
  "Invisalign for Adults Chennai",
  "Invisalign for Adults Pallavaram",
  "Invisalign for Teens in Anakaputhur",
  "Best Invisalign Dentist in Chennai",
  "Teeth Straightening",
  "Teeth straightening in Chennai",
  "Teeth straightening in Pallavaram",
  "Teeth straightening in Anakaputhur",
  "Teeth straightening in Chromepet",
  "Teeth straightening in Pammal",
  "Teeth Straightening with Braces in Kundrathur",
  "Invisible braces",
  "Invisible braces in Chennai",
  "Invisible braces in Pallavaram",
  "Invisible braces in Anakaputhur",
  "Invisible braces in Pammal",
  "Metal braces in Kundrathur",
  "Metal Braces Chromepet",
  "Lingual braces in Chromepet",
  "Lingual braces in Tambaram",
  "Ceramic Braces Chromepet",
  "Ceramic braces in Pallavaram",
  "Metal-Free braces in Chennai",
  "Clear Braces Anakaputhur",
  "Clear Braces in Chromepet",
  "Clear Braces in Kundrathur",
  "Best Clear Braces in Chennai",
  "Self-ligating braces in Chennai",
  "Invisalign Braces Chennai",
  "Teeth Cleaning",
  "Teeth Cleaning Chennai",
  "Teeth Cleaning in Kundrathur",
  "Teeth Cleaning in Tambaram",
  "Teeth Cleaning in Pammal",
  "Teeth Cleaning in Anakaputhur",
  "Teeth Cleaning in Chromepet",
  "Dental Cleaning in Chennai",
  "Best Teeth Cleaning in Pallavaram",
  "Deep Teeth Cleaning in Pammal",
  "Dental Checkup",
  "Dental Checkup in Chromepet",
  "Dental Checkup in Pallavaram",
  "Teeth Whitening",
  "Teeth Whitening in Chennai",
  "Teeth Whitening in Anakaputhur",
  "Teeth Whitening in Pallavaram",
  "Teeth Whitening in Pammal",
  "Teeth Whitening in Chromepet",
  "Teeth Whitening in Kundrathur",
  "Teeth Whitening in Tambaram",
  "Teeth Whitening in Mangadu",
  "Teeth Whitening near Porur",
  "Best Teeth Whitening in Kundrathur",
  "Best Teeth Whitening Services in Anakaputhur",
  "Teeth Whitening Kits Chennai",
  "Laser Teeth Whitening Pallavaram",
  "Laser Dentistry",
  "Laser Dentistry in Chennai",
  "Laser Dentistry in Pallavaram",
  "Laser Dentistry in Anakaputhur",
  "Laser Dentistry in Tambaram",
  "Cosmetic Dentistry",
  "Cosmetic Dentistry in Chennai",
  "Cosmetic Dentistry in Anakaputhur",
  "Cosmetic Dentistry in Pallavaram",
  "Cosmetic Dentistry in Pammal",
  "Cosmetic Dentistry in Chromepet",
  "Cosmetic Dentistry in Kundrathur",
  "Cosmetic Dentist Chennai",
  "Cosmetic Dentistry for Kids in Chennai",
  "Cosmetic Dental Surgeon in Chennai",
  "Cosmetic Dental Surgeon in Anakaputhur",
  "Cosmetic Dental Clinic in Chennai",
  "Cosmetic Dental Treatment Chennai",
  "Cosmetic Bonding",
  "Cosmetic Bonding Chromepet",
  "Cosmetic Bonding in Anakaputhur",
  "Cosmetic Bonding in Pammal",
  "Cosmetic Veneers",
  "Dental Veneers",
  "Dental Veneers in Chennai",
  "Dental Veneers in Pallavaram",
  "Dental Veneers in Anakaputhur",
  "Dental Veneers in Chromepet",
  "Dental Veneers in Kundrathur",
  "Veneers for Crooked Teeth Pammal",
  "Veneers Specialist Chennai",
  "Best Veneers in Chennai",
  "Porcelain Veneers",
  "Porcelain Veneers in Tambaram",
  "Porcelain Veneers Pallavaram",
  "Veneers near Madipakkam",
  "Smile Makeover",
  "Smile Makeover in Chennai",
  "Smile Makeover in Pallavaram",
  "Smile Makeover in Anakaputhur",
  "Smile Makeover in Chromepet",
  "Smile Makeover in Tambaram",
  "Smile Design",
  "Smile Design in Tambaram",
  "Smile Design in Kundrathur",
  "Smile Designing Chennai",
  "Smile Designing in Pammal",
  "Smile Designing in Pallavaram",
  "Smile Designing in Kundrathur",
  "Smile Correction",
  "Smile Correction in Pammal",
  "Dental Fillings",
  "Dental Fillings in Chromepet",
  "Dental Fillings in Anakaputhur",
  "Dental Fillings in Pallavaram",
  "Dental Fillings in Pammal",
  "Dental Fillings in Tambaram",
  "Composite Fillings",
  "Composite Fillings in Chennai",
  "Composite Fillings in Pallavaram",
  "Broken Tooth Repair",
  "Broken Tooth Repair in Chennai",
  "Broken Tooth Repair in Pallavaram",
  "Broken Tooth Repair in Chromepet",
  "Broken Tooth Repair in Anakaputhur",
  "Dental Fillings Anakaputhur",
  "Tooth-Colored Fillings in Anakaputhur",
  "Dental Gap Filling",
  "Teeth Gap Filling",
  "Teeth Gap Filling in Chennai",
  "Teeth Gap Filling in Pallavaram",
  "Teeth Gap Filling in Chromepet",
  "Tooth Bonding",
  "Tooth Bonding in Anakaputhur",
  "Dental Bonding in Tambaram",
  "Crowns and Bridges",
  "Crowns and Bridges in Anakaputhur",
  "Crowns and Bridges in Pallavaram",
  "Crowns and Bridges in Chromepet",
  "Crowns and Bridges in Tambaram",
  "Dental Crowns",
  "Dental Crowns in Chennai",
  "Dental Crowns in Anakaputhur",
  "Dental Crowns in Pallavaram",
  "Dental Crowns in Pammal",
  "Dental Crowns in Chromepet",
  "Dental Crowns in Kundrathur",
  "Zirconia Crowns",
  "Zirconia Crowns in Chennai",
  "Zirconia Crowns in Pallavaram",
  "Dental Crowns Pallavaram",
  "Dental Crowns and Bridges Mangadu",
  "Metal-Free Crowns in Chromepet",
  "Metal-Free Crowns in Chennai",
  "Full Mouth Rehabilitation",
  "Full Mouth Rehabilitation in Chennai",
  "Full Mouth Rehabilitation in Pallavaram",
  "Full Mouth Rehabilitation in Anakaputhur",
  "Full Mouth Rehabilitation in Chromepet",
  "Full Mouth Dental Reconstruction in Chennai",
  "Dental Nightguards",
  "Dental Nightguards in Chennai",
  "Dental Nightguards in Pallavaram",
  "Dental Nightguards in Chromepet",
  "Dental Nightguards in Anakaputhur",
  "Dentures",
  "Best Dentures Service",
  "Best Dentures in Anakaputhur",
  "Denture Specialist Pallavaram",
  "Flexible Dentures Pammal",
  "Dentures in Chennai",
  "Dentures in Anakaputhur",
  "Complete Dentures Pallavaram",
  "Partial Dentures in Pammal",
  "Implant-Supported Dentures in Chennai",
  "Dental Bridges",
  "Dental Bridges in Kundrathur",
  "Dental Bridges near Porur",
  "Prosthodontics",
  "Prosthodontics in Chennai",
  "Prosthodontics in Pallavaram",
  "Prosthodontics in Pammal",
  "Prosthodontics in Anakaputhur",
  "Prosthodontics in Chromepet",
  "Prosthodontics in Kundrathur",
  "Endodontics",
  "Endodontics in Chennai",
  "Endodontics in Pallavaram",
  "Endodontics in Pammal",
  "Endodontics in Chromepet",
  "Endodontics in Anakaputhur",
  "Oral Surgery",
  "Oral Surgery in Chennai",
  "Oral Surgery in Pallavaram",
  "Oral Surgery in Chromepet",
  "Oral Surgery in Anakaputhur",
  "Oral Surgery in Kundrathur",
  "Dental X-rays",
  "Dental X-rays in Chennai",
  "Dental X-rays in Pallavaram",
  "Dental X-rays in Chromepet",
  "Dental X-rays in Anakaputhur",
  "Dental X-rays in Pammal",
  "Maxillofacial Surgery",
  "Maxillofacial Surgery in Chennai",
  "Maxillofacial Surgery in Pallavaram",
  "Orthognathic Surgery",
  "Orthognathic Surgery in Anakaputhur",
  "Jaw Surgery",
  "Jaw Surgery in Chennai",
  "Facial Trauma Surgery Chromepet",
  "Gum Surgery",
  "Gum Surgery in Chennai",
  "Gum Surgery in Pallavaram",
  "Gum Surgery in Anakaputhur",
  "Gum Surgery in Chromepet",
  "Gum Surgery in Kundrathur",
  "Gum Disease Treatment",
  "Gum Disease Treatment in Chennai",
  "Gum Disease Treatment in Pallavaram",
  "Gum Disease Treatment in Chromepet",
  "Gum Disease Treatment in Anakaputhur",
  "Gum Disease Treatment in Kundrathur",
  "Gum Grafting",
  "Gum Grafting in Chennai",
  "Gum Grafting in Pallavaram",
  "Gum Grafting in Anakaputhur",
  "Gum Grafting in Pammal",
  "Gum Grafting in Chromepet",
  "Gum Care",
  "Gum Care in Pallavaram",
  "Gingivitis Treatment",
  "Gingivitis Treatment in Chennai",
  "Gingivitis Treatment in Pallavaram",
  "Gingivitis Treatment in Chromepet",
  "Gingivitis Treatment in Pammal",
  "Gingivitis Treatment in Anakaputhur",
  "Periodontal Treatment",
  "Periodontal Treatment in Chennai",
  "Periodontal Treatment in Pallavaram",
  "Periodontal Treatment in Chromepet",
  "Periodontal Treatment in Anakaputhur",
  "Periodontal Treatment in Pammal",
  "Periodontics",
  "Periodontics in Chennai",
  "Periodontics in Pallavaram",
  "Periodontics in Pammal",
  "Periodontics in Chromepet",
  "Periodontics in Anakaputhur",
  "Periodontist",
  "Periodontist in Chennai",
  "Periodontist in Pallavaram",
  "Periodontist in Anakaputhur",
  "Periodontist in Chromepet",
  "Periodontist in Kundrathur",
  "Gum Specialist",
  "Gum Specialist in Pammal",
  "Gum Surgery Specialist in Pallavaram",
  "TMJ Treatment",
  "TMJ Treatment in Chennai",
  "TMJ Treatment in Pallavaram",
  "TMJ Treatment in Anakaputhur",
  "TMJ Treatment in Chromepet",
  "TMJ Treatment in Tambaram",
  "TMJ Specialist in Chennai",
  "Oral Cancer Screening",
  "Oral Cancer Screening in Chennai",
  "Oral Cancer Screening in Pallavaram",
  "Oral Cancer Screening in Chromepet",
  "Oral Cancer Screening in Anakaputhur",
  "Oral Cancer Screening in Pammal",
  "Tooth Extraction",
  "Tooth Extraction in Chennai",
  "Tooth Extraction in Pallavaram",
  "Tooth Extraction in Chromepet",
  "Tooth Extraction in Pammal",
  "Tooth Extraction in Kundrathur",
  "Surgical Tooth Extraction",
  "Surgical Tooth Extraction in Tambaram",
  "Surgical Tooth Extraction in Chromepet",
  "Tooth Impaction Surgery",
  "Tooth Impaction Surgery in Chennai",
  "Tooth Impaction Surgery in Pallavaram",
  "Tooth Impaction Surgery in Anakaputhur",
  "Tooth Impaction Surgery in Pammal",
  "Tooth Impaction Surgery in Chromepet",
  "Tooth Abscess Treatment",
  "Tooth Abscess Treatment in Chennai",
  "Tooth Abscess Treatment in Pallavaram",
  "Tooth Abscess Treatment in Chromepet",
  "Tooth Abscess Treatment in Anakaputhur",
  "Cracked Tooth Repair",
  "Cracked Tooth Repair in Chennai",
  "Cracked Tooth Repair in Pallavaram",
  "Cracked Tooth Repair in Anakaputhur",
  "Cracked Tooth Repair in Chromepet",
  "Emergency Dental Care",
  "Emergency Dental Care in Chennai",
  "Emergency Dental Care in Pallavaram",
  "Emergency Dental Care in Anakaputhur",
  "Emergency Dental Care in Chromepet",
  "Emergency Tooth Extraction",
  "Emergency Tooth Extraction in Chennai",
  "Emergency Tooth Extraction in Pallavaram",
  "Emergency Tooth Extraction in Anakaputhur",
  "Emergency Tooth Extraction in Chromepet",
  "Emergency Dental Surgery in Chennai",
  "Emergency Dental Services",
  "Emergency Dental Services Chennai",
  "Emergency Dental Services in Pallavaram",
  "Family Dentist",
  "Family Dentist in Chennai",
  "Family Dentist in Pallavaram",
  "Family Dentist in Pammal",
  "Family Dentist in Anakaputhur",
  "Family Dentist in Chromepet",
  "Family Dentistry",
  "Family Dentistry in Kundrathur",
  "Family Dental Services Pallavaram",
  "Family Dental Services in Chennai",
  "Dental Clinic",
  "Dental Clinic in Anakaputhur",
  "Dental Clinic in Pallavaram",
  "Dental Clinic in Pammal",
  "Dental Clinic in Chromepet",
  "Dental Clinic in Kundrathur",
  "Dental Clinic in Tambaram",
  "Dental Clinic in Porur",
  "Dental Clinic near Anakaputhur",
  "Dental Clinic near Pallavaram",
  "Dental Clinic near Pammal",
  "Dental Clinic near Chromepet",
  "Dental Clinic near Kundrathur",
  "Dental Clinic near Tambaram",
  "Dental Clinic near Porur",
  "Dental Clinic near Mangadu",
  "Dental Clinic near Thiruneermalai",
  "Dental Care in Anakaputhur",
  "Dental Care in Chennai",
  "Dental Care in Pallavaram",
  "Dental Care in Pammal",
  "Dental Care in Chromepet",
  "Dental Care in Kundrathur",
  "Dental Health",
  "Dental Health Care Chennai",
  "Dental Health Care in Anakaputhur",
  "Dental Health Services in Chennai",
  "Dental Treatment",
  "Dental Treatment Pallavaram",
  "Dental Treatment for Kids Pallavaram",
  "Dental Treatment in Chennai",
  "Preventive Dentistry",
  "Preventive Dentistry in Chennai",
  "Preventive Dentistry in Pallavaram",
  "Preventive Dentistry in Pammal",
  "Preventive Dentistry in Anakaputhur",
  "Preventive Dentistry in Chromepet",
  "Restorative Dentistry",
  "Restorative Dentistry in Chennai",
  "Restorative Dentistry in Pallavaram",
  "Restorative Dentistry in Anakaputhur",
  "Restorative Dentistry in Chromepet",
  "Dental Hygienist",
  "Dental Hygienist Chennai",
  "Dental Hygienist in Anakaputhur",
  "Dental Hygiene",
  "Dental Hygiene in Chennai",
  "Dental Hygiene in Pallavaram",
  "Dental Hygiene in Chromepet",
  "Dental Hygiene in Anakaputhur",
  "Dental Hygiene in Pammal",
  "Dental Hygiene in Kundrathur",
  "Dental Hygiene Services in Chennai",
  "Dental Plaque Removal",
  "Dental Plaque Removal in Chromepet",
  "Dental Plaque Removal in Anakaputhur",
  "Fluoride Treatment",
  "Fluoride Treatment Chennai",
  "Fluoride Treatment in Pallavaram",
  "Fluoride Treatment in Pammal",
  "Kids Dentistry",
  "Kids Dentistry in Chennai",
  "Kids Dentistry in Pallavaram",
  "Kids Dentistry in Pammal",
  "Kids Dentistry in Anakaputhur",
  "Pediatric Dentistry",
  "Pediatric Dentist",
  "Pediatric Dentist in Chromepet",
  "Pediatric Dentist in Kundrathur",
  "Pediatric Dental Specialist in Pallavaram",
  "Pediatric Cavity Fillings Chromepet",
  "Pediatric Dental Clinic Chromepet",
  "Pediatric Dental Services Chennai",
  "Pediatric Dental Services in Chennai",
  "Affordable Dental Care",
  "Affordable Dental Care in Chennai",
  "Affordable Dental Care in Pallavaram",
  "Affordable Dental Care in Pammal",
  "Affordable Dental Care in Anakaputhur",
  "Affordable Dental Care in Chromepet",
  "Affordable Root Canal in Anakaputhur",
  "Affordable Dentist",
  "Affordable Dentist in Anakaputhur",
  "Affordable Dentist in Chromepet",
  "Affordable Pediatric Dentistry in Pallavaram",
  "Affordable Dental Services",
  "Affordable Dental Services in Chennai",
  "Pallavaram Dental Services",
  "Best Dental Care in Porur",
  "Best Pediatric Dental Care in Pallavaram",
  "Best Dentist in Chennai",
  "Best Dentist in Pallavaram",
  "Best Dentist in Pammal",
  "Best Dentist in Chromepet",
  "Best Dentist in Kundrathur",
  "Best Dentist in Tambaram",
  "Best Dentist in Porur",
  "Best Dentist in Meenambakkam",
  "Best Pediatric Dental Clinic Chennai",
  "Best Pediatric Dental Clinic in Pallavaram",
  "Best Smile Makeover in Chennai",
  "Best Dental Checkup in Chromepet",
  "Best Teeth Whitening Services in Chennai",
  "Best Teeth Cleaning Services in Pallavaram",
  "Single Sitting Root Canal Pallavaram",
  "Tooth Sensitivity Treatment",
  "Tooth Sensitivity Treatment in Chennai",
  "Tooth Sensitivity Treatment in Pallavaram",
  "Tooth Sensitivity Treatment in Chromepet",
  "Tooth Sensitivity Treatment in Anakaputhur",
  "Tooth Reshaping",
  "Tooth Reshaping in Chennai",
  "Toothache Relief",
  "Toothache Relief in Chennai",
  "Toothache Relief in Pallavaram",
  "Toothache Relief in Chromepet",
  "Toothache Relief in Anakaputhur",
  "Toothache Relief in Pammal",
  "Toothache Relief in Kundrathur",
  "Cavity Filling",
  "Cavity Filling in Pallavaram",
  "Cavity Filling in Chennai",
  "Dental Abscess Treatment",
  "Dental Abscess Treatment Pallavaram",
  "Tooth Decay Treatment in Chromepet",
  "Cavity Protection in Kundrathur",
  "Dental Decay Removal Chennai",
  "Cavity Treatment",
  "Cavity Treatment in Pallavaram",
  "Sedation Dentistry",
  "Sedation Dentistry in Chennai",
  "Sedation Dentistry in Pallavaram",
  "Sedation Dentistry in Anakaputhur",
  "Sedation Dentistry in Chromepet",
  "Smile Correction in Chennai",
  "Emergency Toothache Treatment Chennai",
  "Emergency Dentist",
  "Emergency Dentist in Chennai",
  "Emergency Dentist in Pallavaram",
  "Dental Emergency Services in Pallavaram",
  "Dental Emergency Care in Anakaputhur",
  "Dental Emergency Care in Chennai",
  "Dental Emergency Care in Chromepet",
  "Dental Emergency Extraction in Pallavaram",
  "Dental Emergency Surgery in Chennai",
  "Dental Consultation Chennai",
  "Dental Surgeon",
  "Dental Surgeon in Chennai",
  "Dental Surgeon in Pallavaram",
  "Dental Surgeon in Anakaputhur",
  "Dental Surgeon in Chromepet",
  "Dental Surgeon in Pammal",
  "Best Dental Surgeon in Chennai",
  "Affordable Dental Crowns in Chennai",
  "Root Canal Surgeon Chennai",
  "Root Canal Clinic in Chennai",
];
